/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    A4Viewer: typeof import('./src/components/misc/a4Viewer.vue')['default']
    Addpart: typeof import('./src/components/form/addpart.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppPreload: typeof import('./src/components/misc/appPreload.vue')['default']
    AppTools: typeof import('./src/components/misc/appTools.vue')['default']
    EditHeader: typeof import('./src/components/form/editHeader.vue')['default']
    EditInsItem: typeof import('./src/components/form/editInsItem.vue')['default']
    EditInstItem: typeof import('./src/components/form/editInstItem.vue')['default']
    EditPart: typeof import('./src/components/form/editPart.vue')['default']
    EditRole: typeof import('./src/components/form/editRole.vue')['default']
    EditUser: typeof import('./src/components/form/editUser.vue')['default']
    EditWp: typeof import('./src/components/form/editWp.vue')['default']
    ExtInspection: typeof import('./src/components/misc/extInspection.vue')['default']
    FeatureMenus: typeof import('./src/components/misc/featureMenus.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Initiate: typeof import('./src/components/inspection/initiate.vue')['default']
    InspectionForm: typeof import('./src/components/form/inspectionForm.vue')['default']
    InspectionStep: typeof import('./src/components/inspection/inspectionStep.vue')['default']
    InspectionStep_kneadingA: typeof import('./src/components/inspection/inspectionStep_kneadingA.vue')['default']
    InsTable: typeof import('./src/components/misc/insTable.vue')['default']
    KneadingAform: typeof import('./src/components/form/kneadingAform.vue')['default']
    KneadingInspection: typeof import('./src/components/form/kneadingInspection.vue')['default']
    LoginForm: typeof import('./src/components/form/loginForm.vue')['default']
    NewInsItem: typeof import('./src/components/form/newInsItem.vue')['default']
    NewInspectionForm: typeof import('./src/components/form/newInspectionForm.vue')['default']
    NewinspectionItem: typeof import('./src/components/form/newinspectionItem.vue')['default']
    NewMethod: typeof import('./src/components/form/newMethod.vue')['default']
    NewRole: typeof import('./src/components/form/newRole.vue')['default']
    NewUser: typeof import('./src/components/form/newUser.vue')['default']
    NewWpType: typeof import('./src/components/form/newWpType.vue')['default']
    NgPreview: typeof import('./src/components/inspection/ngPreview.vue')['default']
    OutgoingInspection: typeof import('./src/components/inspection/outgoingInspection.vue')['default']
    ReportTable: typeof import('./src/components/misc/reportTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SetupMenus: typeof import('./src/components/misc/setupMenus.vue')['default']
    VideoViewer: typeof import('./src/components/misc/videoViewer.vue')['default']
  }
}
