/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    A4Viewer: typeof import('./src/components/misc/a4Viewer.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppPreload: typeof import('./src/components/misc/appPreload.vue')['default']
    AppTools: typeof import('./src/components/misc/appTools.vue')['default']
    copy: typeof import('./src/components/form/newWpType copy.vue')['default']
    EditInsItem: typeof import('./src/components/form/editInsItem.vue')['default']
    EditInstItem: typeof import('./src/components/form/editInstItem.vue')['default']
    EditPart: typeof import('./src/components/form/editPart.vue')['default']
    EditRole: typeof import('./src/components/form/editRole.vue')['default']
    EditUser: typeof import('./src/components/form/editUser.vue')['default']
    EditWp: typeof import('./src/components/form/editWp.vue')['default']
    FeatureMenu: typeof import('./src/components/misc/featureMenu.vue')['default']
    FeatureMenus: typeof import('./src/components/misc/featureMenus.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InspectionForm: typeof import('./src/components/form/inspectionForm.vue')['default']
    Kneadin_B_form: typeof import('./src/components/form/kneading_B_form.vue')['default']
    Kneading_B_form: typeof import('./src/components/form/kneading_B_form.vue')['default']
    KneadingAform: typeof import('./src/components/form/kneadingAform.vue')['default']
    KneadingBform: typeof import('./src/components/form/kneadingBform.vue')['default']
    KneadingInspection: typeof import('./src/components/form/kneadingInspection.vue')['default']
    LoginForm: typeof import('./src/components/form/loginForm.vue')['default']
    NewInsItem: typeof import('./src/components/form/newInsItem.vue')['default']
    NewInspection: typeof import('./src/components/form/newInspection.vue')['default']
    NewInspectionForm: typeof import('./src/components/form/newInspectionForm.vue')['default']
    NewInstpectionItem: typeof import('./src/components/form/newInstpectionItem.vue')['default']
    NewKneadingItem: typeof import('./src/components/form/newKneadingItem.vue')['default']
    NewMethod: typeof import('./src/components/form/newMethod.vue')['default']
    NewPart: typeof import('./src/components/form/newPart.vue')['default']
    NewRole: typeof import('./src/components/form/newRole.vue')['default']
    NewUser: typeof import('./src/components/form/newUser.vue')['default']
    NewWpType: typeof import('./src/components/form/newWpType.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SetupMenus: typeof import('./src/components/misc/setupMenus.vue')['default']
  }
}
