/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppPreload: typeof import('./src/components/misc/appPreload.vue')['default']
    AppTools: typeof import('./src/components/misc/appTools.vue')['default']
    copy: typeof import('./src/components/form/newRole copy.vue')['default']
    EditRole: typeof import('./src/components/form/editRole.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LoginForm: typeof import('./src/components/form/loginForm.vue')['default']
    NewRole: typeof import('./src/components/form/newRole.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SetupMenus: typeof import('./src/components/misc/setupMenus.vue')['default']
  }
}
